services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FriendsOfTYPO3\Widgets\:
    resource: '../Classes/*'

  FriendsOfTYPO3\Widgets\Widgets\Provider\PagesWithoutDescriptionDataProvider:
    arguments:
      $excludedDoktypes: [3, 4, 6, 7, 199, 254, 255]
      $limit: 8

  FriendsOfTYPO3\Widgets\Widgets\Provider\StatusReportButtonProvider:
    arguments:
      $title: 'LLL:EXT:widgets/Resources/Private/Language/locallang.xlf:widgets.dashboard.widget.statusReport.button.title'

  widgets.dashboard.widget.onlineUsers:
    class: 'FriendsOfTYPO3\Widgets\Widgets\ExtendedListWidget'
    arguments:
      $dataProvider: '@FriendsOfTYPO3\Widgets\Widgets\Provider\UsersOnlineDataProvider'
      $view: '@dashboard.views.widget'
      $options:
        template: 'Widget/UsersOnlineWidget'
    tags:
      - name: dashboard.widget
        identifier: 'widgets-onlineUsers'
        groupNames: 'systemInfo'
        title: 'LLL:EXT:widgets/Resources/Private/Language/locallang.xlf:widgets.dashboard.widget.onlineUsers.title'
        description: 'LLL:EXT:widgets/Resources/Private/Language/locallang.xlf:widgets.dashboard.widget.onlineUsers.description'
        iconIdentifier: 'content-widget-list'
        height: 'large'
        width: 'medium'

  dashboard.widget.reports:
    class: 'FriendsOfTYPO3\Widgets\Widgets\StatusReportWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $buttonProvider: '@FriendsOfTYPO3\Widgets\Widgets\Provider\StatusReportButtonProvider'
      $options:
        template: 'Widget/UsersOnlineWidget'
    tags:
      - name: dashboard.widget
        identifier: 'widgets-statusReport'
        groupNames: 'systemInfo'
        title: 'LLL:EXT:widgets/Resources/Private/Language/locallang.xlf:widgets.dashboard.widget.statusReport.title'
        description: 'LLL:EXT:widgets/Resources/Private/Language/locallang.xlf:widgets.dashboard.widget.statusReport.description'
        iconIdentifier: 'content-widget-list'
        height: 'medium'
        width: 'medium'

  widgets.dashboard.widget.contact:
    class: 'FriendsOfTYPO3\Widgets\Widgets\ContactWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $options:
        template: 'Widget/ContactWidget'
        introTextLl: ''
        company: 'Your TYPO3 agency'
        address: '-'
        postalCode: '-'
        place: '-'
        tel: '-'
        mail: '-'
        website: '-'
        logoPath: 'logopath.svg'
    tags:
      - name: dashboard.widget
        identifier: 'widgets-contact'
        groupNames: 'general'
        title: 'LLL:EXT:widgets/Resources/Private/Language/locallang.xlf:widgets.dashboard.widget.contact.title'
        description: 'LLL:EXT:widgets/Resources/Private/Language/locallang.xlf:widgets.dashboard.widget.contact.description'
        iconIdentifier: 'content-widget-list'
        height: 'medium'
        width: 'small'
