services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FriendsOfTYPO3\Widgets\:
    resource: '../Classes/*'

  FriendsOfTYPO3\Widgets\Widgets\Provider\PagesWithoutDescriptionDataProvider:
    arguments:
      $excludedDoktypes: [3, 4, 6, 7, 199, 254, 255]
      $limit: 8

  FriendsOfTYPO3\Widgets\Widgets\Provider\StatusReportButtonProvider:
    arguments:
      $title: 'LLL:EXT:widgets/Resources/Private/Language/locallang.xlf:widgets.dashboard.widget.statusReport.button.title'

  widgets.dashboard.widget.onlineUsers:
    class: 'FriendsOfTYPO3\Widgets\Widgets\ExtendedListWidget'
    arguments:
      $dataProvider: '@FriendsOfTYPO3\Widgets\Widgets\Provider\UsersOnlineDataProvider'
      $view: '@dashboard.views.widget'
      $options:
        template: 'Widget/UsersOnlineWidget'
    tags:
      - name: dashboard.widget
        identifier: 'widgets-onlineUsers'
        groupNames: 'systemInfo'
        title: 'LLL:EXT:widgets/Resources/Private/Language/locallang.xlf:widgets.dashboard.widget.onlineUsers.title'
        description: 'LLL:EXT:widgets/Resources/Private/Language/locallang.xlf:widgets.dashboard.widget.onlineUsers.description'
        iconIdentifier: 'content-widget-list'
        height: 'large'
        width: 'medium'

  dashboard.widget.reports:
    class: 'FriendsOfTYPO3\Widgets\Widgets\StatusReportWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $buttonProvider: '@FriendsOfTYPO3\Widgets\Widgets\Provider\StatusReportButtonProvider'
      $options:
        template: 'Widget/UsersOnlineWidget'
    tags:
      - name: dashboard.widget
        identifier: 'widgets-statusReport'
        groupNames: 'systemInfo'
        title: 'LLL:EXT:widgets/Resources/Private/Language/locallang.xlf:widgets.dashboard.widget.statusReport.title'
        description: 'LLL:EXT:widgets/Resources/Private/Language/locallang.xlf:widgets.dashboard.widget.statusReport.description'
        iconIdentifier: 'content-widget-list'
        height: 'medium'
        width: 'medium'

  dashboard.buttons.contact:
    class: 'TYPO3\CMS\Dashboard\Widgets\Provider\ButtonProvider'
    arguments:
      $title: 'Find a partner'
      $link: 'https://typo3.com/services/find-a-typo3-partner/official-typo3-partner-finder'
      $target: '_blank'

  widgets.dashboard.widget.contact:
    class: 'FriendsOfTYPO3\Widgets\Widgets\ContactWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $buttonProvider: '@dashboard.buttons.contact'
      $options:
        template: 'Widget/ContactWidget'
        introText: 'LLL:EXT:widgets/Resources/Private/Language/locallang.xlf:widgets.dashboard.widget.contact.defaultIntro'
        company: ''
        address: ''
        postalCode: ''
        place: ''
        country: ''
        tel: ''
        mail: ''
        website: ''
        logoPath: 'EXT:backend/Resources/Public/Images/typo3_orange.svg'
    tags:
      - name: dashboard.widget
        identifier: 'widgets-contact'
        groupNames: 'general'
        title: 'LLL:EXT:widgets/Resources/Private/Language/locallang.xlf:widgets.dashboard.widget.contact.title'
        description: 'LLL:EXT:widgets/Resources/Private/Language/locallang.xlf:widgets.dashboard.widget.contact.description'
        iconIdentifier: 'content-widget-list'
        height: 'medium'
        width: 'small'
